# Generated by Django 5.2.14 on 2026-06-08 15:14

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_caseversion_approval_id_caseversion_bia_result_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('manifest_path', models.CharField(help_text='Path relative to MEDIA_ROOT for the manifest JSON file.', max_length=512)),
                ('manifest_sha256', models.CharField(help_text='SHA-256 of the manifest JSON bytes — tamper detection seal.', max_length=64)),
                ('manifest_size_bytes', models.PositiveIntegerField(default=0)),
                ('retention_until', models.DateTimeField(db_index=True, help_text='Earliest date the archive may be purged. Default = archived_at + 7 years.')),
                ('notes', models.TextField(blank=True, default='')),
                ('artifact_counts', models.JSONField(default=dict, help_text='Inventory summary: {recommendations: N, approvals: M, ...}')),
                ('archived_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archives_created', to=settings.AUTH_USER_MODEL)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='archive_record', to='cases.case')),
            ],
            options={
                'verbose_name': 'Archive Record',
                'verbose_name_plural': 'Archive Records',
                'ordering': ('-archived_at',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalArchiveRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('manifest_path', models.CharField(help_text='Path relative to MEDIA_ROOT for the manifest JSON file.', max_length=512)),
                ('manifest_sha256', models.CharField(help_text='SHA-256 of the manifest JSON bytes — tamper detection seal.', max_length=64)),
                ('manifest_size_bytes', models.PositiveIntegerField(default=0)),
                ('retention_until', models.DateTimeField(db_index=True, help_text='Earliest date the archive may be purged. Default = archived_at + 7 years.')),
                ('notes', models.TextField(blank=True, default='')),
                ('artifact_counts', models.JSONField(default=dict, help_text='Inventory summary: {recommendations: N, approvals: M, ...}')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('archived_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.case')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Archive Record',
                'verbose_name_plural': 'historical Archive Records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
