# Generated by Django 5.2.14 on 2026-06-08 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiverecord',
            name='archived_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Set explicitly by the service so it matches retention_until exactly. Falls back to current time if instantiated outside the service.'),
        ),
        migrations.AlterField(
            model_name='historicalarchiverecord',
            name='archived_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Set explicitly by the service so it matches retention_until exactly. Falls back to current time if instantiated outside the service.'),
        ),
    ]
