# Generated by Django 5.2.14 on 2026-05-25 14:39

import apps.cases.models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "case_id",
                    models.CharField(
                        help_text="Slug seperti HF_ARNI_ACEI_001",
                        max_length=64,
                        unique=True,
                        validators=[apps.cases.models.validate_case_id],
                    ),
                ),
                ("case_title", models.CharField(max_length=255)),
                (
                    "technology",
                    models.CharField(
                        help_text="Intervensi / teknologi yang dievaluasi (mis. Sacubitril/valsartan)",
                        max_length=255,
                    ),
                ),
                ("comparator", models.CharField(max_length=255)),
                ("indication", models.CharField(max_length=255)),
                ("population", models.TextField(blank=True, default="")),
                ("setting", models.CharField(blank=True, default="", max_length=255)),
                (
                    "perspective",
                    models.CharField(
                        choices=[
                            ("hospital", "Rumah Sakit"),
                            ("payer_bpjs", "BPJS / Pembayar"),
                            ("societal", "Masyarakat"),
                        ],
                        default="hospital",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "Dalam tinjauan"),
                            ("approved", "Disetujui"),
                            ("locked", "Terkunci"),
                            ("archived", "Diarsipkan"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Case",
                "verbose_name_plural": "Cases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCase",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "case_id",
                    models.CharField(
                        db_index=True,
                        help_text="Slug seperti HF_ARNI_ACEI_001",
                        max_length=64,
                        validators=[apps.cases.models.validate_case_id],
                    ),
                ),
                ("case_title", models.CharField(max_length=255)),
                (
                    "technology",
                    models.CharField(
                        help_text="Intervensi / teknologi yang dievaluasi (mis. Sacubitril/valsartan)",
                        max_length=255,
                    ),
                ),
                ("comparator", models.CharField(max_length=255)),
                ("indication", models.CharField(max_length=255)),
                ("population", models.TextField(blank=True, default="")),
                ("setting", models.CharField(blank=True, default="", max_length=255)),
                (
                    "perspective",
                    models.CharField(
                        choices=[
                            ("hospital", "Rumah Sakit"),
                            ("payer_bpjs", "BPJS / Pembayar"),
                            ("societal", "Masyarakat"),
                        ],
                        default="hospital",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "Dalam tinjauan"),
                            ("approved", "Disetujui"),
                            ("locked", "Terkunci"),
                            ("archived", "Diarsipkan"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Case",
                "verbose_name_plural": "historical Cases",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDecisionQuestion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=1)),
                ("question_text", models.TextField(help_text="Pertanyaan klinis lengkap")),
                ("pico_population", models.CharField(blank=True, default="", max_length=255)),
                ("pico_intervention", models.CharField(blank=True, default="", max_length=255)),
                ("pico_comparator", models.CharField(blank=True, default="", max_length=255)),
                ("pico_outcome", models.CharField(blank=True, default="", max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cases.case",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Decision Question",
                "verbose_name_plural": "historical Decision Questions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="CaseVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "version_number",
                    models.CharField(
                        help_text="Semantic version, e.g. 0.1.0 or 1.0.0", max_length=32
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft (v0.x)"),
                            ("locked", "Locked (v1.x)"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("lock_reason", models.TextField(blank=True, default="")),
                (
                    "diff",
                    models.JSONField(
                        blank=True, help_text="Field-level diff from prior version", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="case_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_versions_locked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Version",
                "verbose_name_plural": "Case Versions",
                "ordering": ["case", "-created_at"],
                "unique_together": {("case", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="DecisionQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=1)),
                ("question_text", models.TextField(help_text="Pertanyaan klinis lengkap")),
                ("pico_population", models.CharField(blank=True, default="", max_length=255)),
                ("pico_intervention", models.CharField(blank=True, default="", max_length=255)),
                ("pico_comparator", models.CharField(blank=True, default="", max_length=255)),
                ("pico_outcome", models.CharField(blank=True, default="", max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_questions",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "verbose_name": "Decision Question",
                "verbose_name_plural": "Decision Questions",
                "ordering": ["case", "order"],
                "unique_together": {("case", "order")},
            },
        ),
    ]
