# Generated by Django 5.2.14 on 2026-09-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_caseversion_approval_id_caseversion_bia_result_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseversion',
            name='snapshot',
            field=models.JSONField(blank=True, help_text='Immutable value snapshot of the decision at lock time', null=True),
        ),
    ]
