# Generated by Django 5.2.14 on 2026-09-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_caseversion_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='integrity_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='integrity_flag',
            field=models.CharField(blank=True, choices=[('', 'Terverifikasi'), ('requires_remediation', 'Perlu perbaikan'), ('legacy_invalid', 'Warisan tidak valid')], default='', help_text='Hasil integrity check arsip. Kosong berarti lolos.', max_length=24),
        ),
        migrations.AddField(
            model_name='case',
            name='integrity_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='integrity_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='integrity_flag',
            field=models.CharField(blank=True, choices=[('', 'Terverifikasi'), ('requires_remediation', 'Perlu perbaikan'), ('legacy_invalid', 'Warisan tidak valid')], default='', help_text='Hasil integrity check arsip. Kosong berarti lolos.', max_length=24),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='integrity_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
