# Generated by Django 5.2.14 on 2026-05-25 17:01

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CEAInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "drug_cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Biaya obat/teknologi yang dievaluasi per pasien per periode",
                        max_digits=15,
                        verbose_name="Biaya intervensi per unit (IDR)",
                    ),
                ),
                (
                    "comparator_cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Biaya komparator per unit (IDR)",
                    ),
                ),
                (
                    "efficacy_metric",
                    models.CharField(
                        choices=[
                            ("qaly", "QALY (Quality-Adjusted Life Year)"),
                            ("lyg", "LYG (Life Year Gained)"),
                            ("other", "Other (specify in metric_label)"),
                        ],
                        default="qaly",
                        max_length=16,
                    ),
                ),
                (
                    "metric_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Deskripsi metrik bila 'Other' dipilih",
                        max_length=120,
                    ),
                ),
                (
                    "drug_efficacy_value",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Nilai efikasi intervensi"
                    ),
                ),
                (
                    "comparator_efficacy_value",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Nilai efikasi komparator"
                    ),
                ),
                (
                    "patient_population_size",
                    models.PositiveIntegerField(
                        help_text="Jumlah pasien yang akan diberikan intervensi per tahun",
                        verbose_name="Estimasi populasi pasien",
                    ),
                ),
                (
                    "wtop_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("250000000.00"),
                        help_text="Willingness-to-pay per QALY/LYG",
                        max_digits=15,
                        verbose_name="Ambang batas WTOP (IDR per unit efikasi)",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("literature", "Literatur ilmiah"),
                            ("local_data", "Data lokal RS"),
                            ("expert_opinion", "Pendapat ahli"),
                            ("mixed", "Campuran"),
                        ],
                        default="literature",
                        max_length=24,
                    ),
                ),
                ("evidence_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cea_input",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cea_inputs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cea_inputs_edited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CEA Input",
                "verbose_name_plural": "CEA Inputs",
            },
        ),
        migrations.CreateModel(
            name="HistoricalCEAInput",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "drug_cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Biaya obat/teknologi yang dievaluasi per pasien per periode",
                        max_digits=15,
                        verbose_name="Biaya intervensi per unit (IDR)",
                    ),
                ),
                (
                    "comparator_cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Biaya komparator per unit (IDR)",
                    ),
                ),
                (
                    "efficacy_metric",
                    models.CharField(
                        choices=[
                            ("qaly", "QALY (Quality-Adjusted Life Year)"),
                            ("lyg", "LYG (Life Year Gained)"),
                            ("other", "Other (specify in metric_label)"),
                        ],
                        default="qaly",
                        max_length=16,
                    ),
                ),
                (
                    "metric_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Deskripsi metrik bila 'Other' dipilih",
                        max_length=120,
                    ),
                ),
                (
                    "drug_efficacy_value",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Nilai efikasi intervensi"
                    ),
                ),
                (
                    "comparator_efficacy_value",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Nilai efikasi komparator"
                    ),
                ),
                (
                    "patient_population_size",
                    models.PositiveIntegerField(
                        help_text="Jumlah pasien yang akan diberikan intervensi per tahun",
                        verbose_name="Estimasi populasi pasien",
                    ),
                ),
                (
                    "wtop_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("250000000.00"),
                        help_text="Willingness-to-pay per QALY/LYG",
                        max_digits=15,
                        verbose_name="Ambang batas WTOP (IDR per unit efikasi)",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("literature", "Literatur ilmiah"),
                            ("local_data", "Data lokal RS"),
                            ("expert_opinion", "Pendapat ahli"),
                            ("mixed", "Campuran"),
                        ],
                        default="literature",
                        max_length=24,
                    ),
                ),
                ("evidence_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical CEA Input",
                "verbose_name_plural": "historical CEA Inputs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="CEAResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "input_snapshot",
                    models.JSONField(help_text="CEAInput field values at compute time"),
                ),
                ("incremental_cost", models.DecimalField(decimal_places=2, max_digits=15)),
                ("incremental_effect", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "icer_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Null when incremental_effect is ~zero (frontier ambiguous)",
                        max_digits=18,
                        null=True,
                    ),
                ),
                ("wtop_threshold_used", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "dominance",
                    models.CharField(
                        choices=[
                            ("cost_saving", "Cost-saving (dominant)"),
                            ("cost_effective_safe", "Cost-effective (aman)"),
                            ("cost_effective_at_threshold", "Cost-effective (di ambang)"),
                            ("cost_uncertain", "Tidak pasti"),
                            ("cost_ineffective", "Cost-ineffective"),
                            ("dominated", "Dominated (lebih mahal & kurang efektif)"),
                            ("frontier_ambiguous", "Ambigu (efek nol)"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "ce_score",
                    models.PositiveSmallIntegerField(
                        help_text="0-100 contribution to the final traffic-light recommendation"
                    ),
                ),
                (
                    "sensitivity_low_icer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="ICER under 20% adverse variance (cost +20%, effect -20%)",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "sensitivity_high_icer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="ICER under 20% favourable variance (cost -20%, effect +20%)",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "threshold_sensitivity_flag",
                    models.BooleanField(
                        default=False,
                        help_text="True when ICER lies within ±20% of WTOP — review carefully",
                    ),
                ),
                ("interpretation_text", models.TextField(blank=True, default="")),
                ("algorithm_version", models.CharField(default="1.0.0", max_length=16)),
                (
                    "computed_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cea_results",
                        to="cases.case",
                    ),
                ),
                (
                    "computed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cea_results_computed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CEA Result",
                "verbose_name_plural": "CEA Results",
                "ordering": ["-computed_at"],
                "indexes": [
                    models.Index(
                        fields=["case", "-computed_at"], name="cea_cearesu_case_id_763db6_idx"
                    )
                ],
            },
        ),
    ]
