# Generated by Django 5.2.14 on 2026-05-25 02:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login_success", "Login success"),
                            ("login_failed", "Login failed"),
                            ("logout", "Logout"),
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("approve", "Approve"),
                            ("lock", "Lock version"),
                            ("upload", "File upload"),
                            ("download", "File download"),
                            ("permission_denied", "Permission denied"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("target_object_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "diff",
                    models.JSONField(
                        blank=True, help_text="Field-level old/new changes", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, help_text="Extra context (session, reason)", null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=512)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit log entry",
                "verbose_name_plural": "Audit log",
                "ordering": ["-created_at"],
                "permissions": [],
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"], name="audit_audit_action_0c6a84_idx"
                    ),
                    models.Index(
                        fields=["actor", "-created_at"], name="audit_audit_actor_i_1175ab_idx"
                    ),
                    models.Index(
                        fields=["target_content_type", "target_object_id"],
                        name="audit_audit_target__f79146_idx",
                    ),
                ],
            },
        ),
    ]
