# Generated by Django 5.2.14 on 2026-06-01 05:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("recommendation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                            ("revision_requested", "Minta Revisi"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "confirmation_acknowledged",
                    models.BooleanField(
                        default=False,
                        help_text="Checkbox 'Saya konfirmasi...' was ticked at sign time.",
                    ),
                ),
                (
                    "password_verified_at",
                    models.DateTimeField(
                        help_text="Server-side check_password() success timestamp."
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Required for REJECTED and REVISION_REQUESTED.",
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=512)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approvals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="cases.case",
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        help_text="Exact recommendation row that was reviewed and signed.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approvals",
                        to="recommendation.recommendation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval",
                "verbose_name_plural": "Approvals",
                "ordering": ["-signed_at"],
                "indexes": [
                    models.Index(
                        fields=["case", "-signed_at"], name="approval_ap_case_id_afb23e_idx"
                    )
                ],
            },
        ),
    ]
