# Generated by Django 5.2.14 on 2026-05-28 17:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("etd", "0002_seed_domains"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CBACriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "criterion_name",
                    models.CharField(
                        help_text="Nama singkat, mis. 'Diresepkan oleh kardiolog'", max_length=200
                    ),
                ),
                (
                    "field_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Field klinis yang dirujuk, mis. 'prescriber.specialty'",
                        max_length=120,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("equals", "Sama dengan"),
                            ("not_equals", "Tidak sama dengan"),
                            ("greater_than", "Lebih besar dari"),
                            ("less_than", "Lebih kecil dari"),
                            ("in_list", "Dalam daftar (comma-separated)"),
                            ("is_present", "Ada / Terdapat"),
                        ],
                        default="is_present",
                        max_length=24,
                    ),
                ),
                ("expected_value", models.CharField(blank=True, default="", max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "is_satisfied",
                    models.BooleanField(
                        default=False,
                        help_text="Centang manual oleh KFT bila kriteria terpenuhi pada konteks RS",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cba_criteria",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cba_criteria_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cba_criteria_edited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CBA Criterion",
                "verbose_name_plural": "CBA Criteria",
                "ordering": ["case", "order"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCBACriterion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "criterion_name",
                    models.CharField(
                        help_text="Nama singkat, mis. 'Diresepkan oleh kardiolog'", max_length=200
                    ),
                ),
                (
                    "field_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Field klinis yang dirujuk, mis. 'prescriber.specialty'",
                        max_length=120,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("equals", "Sama dengan"),
                            ("not_equals", "Tidak sama dengan"),
                            ("greater_than", "Lebih besar dari"),
                            ("less_than", "Lebih kecil dari"),
                            ("in_list", "Dalam daftar (comma-separated)"),
                            ("is_present", "Ada / Terdapat"),
                        ],
                        default="is_present",
                        max_length=24,
                    ),
                ),
                ("expected_value", models.CharField(blank=True, default="", max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "is_satisfied",
                    models.BooleanField(
                        default=False,
                        help_text="Centang manual oleh KFT bila kriteria terpenuhi pada konteks RS",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical CBA Criterion",
                "verbose_name_plural": "historical CBA Criteria",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDomainWeightVote",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        help_text="Bobot kepentingan 0-100 untuk domain ini menurut anggota",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cases.case",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="etd.etddomain",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Domain Weight Vote",
                "verbose_name_plural": "historical Domain Weight Votes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="DomainWeightVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        help_text="Bobot kepentingan 0-100 untuk domain ini menurut anggota",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_votes",
                        to="cases.case",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weight_votes",
                        to="etd.etddomain",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weight_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain Weight Vote",
                "verbose_name_plural": "Domain Weight Votes",
                "ordering": ["case", "domain__order", "member__email"],
                "indexes": [
                    models.Index(fields=["case", "domain"], name="recommendat_case_id_5d842e_idx")
                ],
                "unique_together": {("case", "domain", "member")},
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "input_snapshot",
                    models.JSONField(
                        help_text="CEA result, BIA result, EtD summary, weights, CBA criteria at compute time"
                    ),
                ),
                (
                    "evidence_strength_score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "ce_score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "budget_score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                ("cba_score", models.DecimalField(decimal_places=2, max_digits=6)),
                ("composite_score", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "traffic_light",
                    models.CharField(
                        choices=[
                            ("green", "HIJAU — Adopsi tanpa syarat"),
                            ("yellow", "KUNING — Adopsi bersyarat (CBA)"),
                            ("red", "MERAH — Tidak direkomendasikan"),
                        ],
                        max_length=8,
                    ),
                ),
                ("justification_text", models.TextField(blank=True, default="")),
                ("cba_criteria_count", models.PositiveSmallIntegerField(default=0)),
                ("cba_satisfied_count", models.PositiveSmallIntegerField(default=0)),
                ("algorithm_version", models.CharField(default="1.0.0", max_length=16)),
                ("weight_aggregation_method", models.CharField(default="mean", max_length=16)),
                (
                    "computed_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="cases.case",
                    ),
                ),
                (
                    "computed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations_computed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation",
                "verbose_name_plural": "Recommendations",
                "ordering": ["-computed_at"],
                "indexes": [
                    models.Index(
                        fields=["case", "-computed_at"], name="recommendat_case_id_f73508_idx"
                    )
                ],
            },
        ),
    ]
