# Generated by Django 5.2.14 on 2026-05-28 10:00

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EtDDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        choices=[
                            ("problem", "Masalah (Problem)"),
                            ("desirable_effects", "Efek yang Diinginkan"),
                            ("undesirable_effects", "Efek yang Tidak Diinginkan"),
                            ("certainty_of_evidence", "Kepastian Bukti"),
                            ("values_preferences", "Nilai & Preferensi"),
                            ("resource_use", "Penggunaan Sumber Daya"),
                            ("equity", "Ekuitas"),
                            ("feasibility", "Kelayakan Implementasi"),
                            ("acceptability", "Penerimaan oleh Pemangku Kepentingan"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("display_name_id", models.CharField(max_length=120)),
                ("display_name_en", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "prompt_text_id",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Pertanyaan panduan yang ditampilkan kepada anggota KFT",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                "verbose_name": "EtD Domain",
                "verbose_name_plural": "EtD Domains",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="EtDAppraisal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "judgement",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Tidak"),
                            (25, "Mungkin tidak"),
                            (50, "Tidak pasti"),
                            (75, "Mungkin ya"),
                            (100, "Ya"),
                        ]
                    ),
                ),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("high", "Tinggi"),
                            ("moderate", "Sedang"),
                            ("low", "Rendah"),
                            ("very_low", "Sangat rendah"),
                        ],
                        default="moderate",
                        max_length=16,
                    ),
                ),
                (
                    "narrative",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Pertimbangan singkat anggota KFT untuk domain ini",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etd_appraisals",
                        to="cases.case",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="etd_appraisals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appraisals",
                        to="etd.etddomain",
                    ),
                ),
            ],
            options={
                "verbose_name": "EtD Appraisal",
                "verbose_name_plural": "EtD Appraisals",
                "ordering": ["case", "domain__order", "member__email"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalEtDAppraisal",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "judgement",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Tidak"),
                            (25, "Mungkin tidak"),
                            (50, "Tidak pasti"),
                            (75, "Mungkin ya"),
                            (100, "Ya"),
                        ]
                    ),
                ),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("high", "Tinggi"),
                            ("moderate", "Sedang"),
                            ("low", "Rendah"),
                            ("very_low", "Sangat rendah"),
                        ],
                        default="moderate",
                        max_length=16,
                    ),
                ),
                (
                    "narrative",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Pertimbangan singkat anggota KFT untuk domain ini",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cases.case",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="etd.etddomain",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical EtD Appraisal",
                "verbose_name_plural": "historical EtD Appraisals",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalReferenceCitation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("journal_article", "Artikel jurnal"),
                            ("clinical_guideline", "Pedoman klinis"),
                            ("institutional_protocol", "Protokol institusi"),
                            ("expert_opinion", "Pendapat ahli"),
                            ("pharmacoeconomic_model", "Model farmakoekonomi"),
                        ],
                        default="journal_article",
                        max_length=32,
                    ),
                ),
                (
                    "citation_text",
                    models.CharField(
                        help_text="Sitasi terformat — author year. title. journal.", max_length=500
                    ),
                ),
                ("authors", models.CharField(blank=True, default="", max_length=300)),
                ("publication_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("journal_name", models.CharField(blank=True, default="", max_length=200)),
                ("doi_pmid", models.CharField(blank=True, default="", max_length=120)),
                ("url", models.URLField(blank=True, default="", max_length=500)),
                ("evidence_summary", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Reference Citation",
                "verbose_name_plural": "historical Reference Citations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ReferenceCitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("journal_article", "Artikel jurnal"),
                            ("clinical_guideline", "Pedoman klinis"),
                            ("institutional_protocol", "Protokol institusi"),
                            ("expert_opinion", "Pendapat ahli"),
                            ("pharmacoeconomic_model", "Model farmakoekonomi"),
                        ],
                        default="journal_article",
                        max_length=32,
                    ),
                ),
                (
                    "citation_text",
                    models.CharField(
                        help_text="Sitasi terformat — author year. title. journal.", max_length=500
                    ),
                ),
                ("authors", models.CharField(blank=True, default="", max_length=300)),
                ("publication_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("journal_name", models.CharField(blank=True, default="", max_length=200)),
                ("doi_pmid", models.CharField(blank=True, default="", max_length=120)),
                ("url", models.URLField(blank=True, default="", max_length=500)),
                ("evidence_summary", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="references_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reference Citation",
                "verbose_name_plural": "Reference Citations",
                "ordering": ["case", "-publication_year", "authors"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalEtDAppraisal_references",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "etdappraisal",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="etd.etdappraisal",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="etd.historicaletdappraisal",
                    ),
                ),
                (
                    "referencecitation",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="etd.referencecitation",
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalEtDAppraisal_references",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="etdappraisal",
            name="references",
            field=models.ManyToManyField(
                blank=True, related_name="appraisals", to="etd.referencecitation"
            ),
        ),
        migrations.AddIndex(
            model_name="etdappraisal",
            index=models.Index(fields=["case", "domain"], name="etd_etdappr_case_id_ae5d48_idx"),
        ),
        migrations.AddIndex(
            model_name="etdappraisal",
            index=models.Index(fields=["case", "member"], name="etd_etdappr_case_id_aa8989_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="etdappraisal",
            unique_together={("case", "domain", "member")},
        ),
    ]
