# Generated by Django 5.2.14 on 2026-05-25 02:14

import apps.accounts.managers
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="email address"),
                ),
                ("full_name", models.CharField(max_length=180, verbose_name="full name")),
                (
                    "nip",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Indonesian government / hospital staff identifier",
                        max_length=32,
                        verbose_name="NIP / staff ID",
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True, default="", max_length=180, verbose_name="institution"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_staff",
                    models.BooleanField(default=False, help_text="Can access Django admin"),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["email"],
            },
            managers=[
                ("objects", apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        choices=[
                            ("admin_it", "Admin IT"),
                            ("hta_analyst", "HTA Analyst / Farmakoekonomi"),
                            ("farmasi_sekretaris", "Farmasi RS / Sekretaris KFT"),
                            ("kft_member", "Anggota KFT"),
                            ("ketua_kft", "Ketua KFT / Approver"),
                        ],
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "display_name_id",
                    models.CharField(max_length=120, verbose_name="Indonesian display name"),
                ),
                (
                    "display_name_en",
                    models.CharField(max_length=120, verbose_name="English display name"),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["slug"],
            },
        ),
    ]
