# Generated by Django 5.2.14 on 2026-09-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Set by Admin IT to force a password change at next sign-in. Admin IT never sets or sees a password itself.'),
        ),
    ]
