# Generated by Django 5.2.14 on 2026-05-27 09:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BIAInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "eligible_population",
                    models.PositiveIntegerField(
                        help_text="Jumlah pasien per tahun yang berpotensi menerima intervensi",
                        verbose_name="Estimasi populasi pasien yang memenuhi syarat",
                    ),
                ),
                (
                    "patient_uptake_year1",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Proporsi pasien yang menerima intervensi pada Tahun 1, contoh 0.30 untuk 30%",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Uptake tahun 1 (0-1)",
                    ),
                ),
                (
                    "patient_uptake_year3",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Uptake tahun 3 (0-1)",
                    ),
                ),
                (
                    "market_share_year1",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Pangsa pasar tahun 1 (0-1)",
                    ),
                ),
                (
                    "market_share_year3",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Pangsa pasar tahun 3 (0-1)",
                    ),
                ),
                (
                    "unit_cost_drug",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Biaya intervensi per pasien per tahun (IDR)",
                    ),
                ),
                (
                    "unit_cost_comparator",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Biaya komparator per pasien per tahun (IDR)",
                    ),
                ),
                (
                    "budget_baseline",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total anggaran obat RS per tahun — digunakan untuk hitung % dampak",
                        max_digits=18,
                        verbose_name="Anggaran farmasi tahunan baseline (IDR)",
                    ),
                ),
                (
                    "projection_horizon",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1 tahun"), (3, "3 tahun")],
                        default=3,
                        verbose_name="Horison proyeksi (tahun)",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bia_input",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bia_inputs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bia_inputs_edited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "BIA Input",
                "verbose_name_plural": "BIA Inputs",
            },
        ),
        migrations.CreateModel(
            name="HistoricalBIAInput",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "eligible_population",
                    models.PositiveIntegerField(
                        help_text="Jumlah pasien per tahun yang berpotensi menerima intervensi",
                        verbose_name="Estimasi populasi pasien yang memenuhi syarat",
                    ),
                ),
                (
                    "patient_uptake_year1",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Proporsi pasien yang menerima intervensi pada Tahun 1, contoh 0.30 untuk 30%",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Uptake tahun 1 (0-1)",
                    ),
                ),
                (
                    "patient_uptake_year3",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Uptake tahun 3 (0-1)",
                    ),
                ),
                (
                    "market_share_year1",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Pangsa pasar tahun 1 (0-1)",
                    ),
                ),
                (
                    "market_share_year3",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Pangsa pasar tahun 3 (0-1)",
                    ),
                ),
                (
                    "unit_cost_drug",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Biaya intervensi per pasien per tahun (IDR)",
                    ),
                ),
                (
                    "unit_cost_comparator",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Biaya komparator per pasien per tahun (IDR)",
                    ),
                ),
                (
                    "budget_baseline",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total anggaran obat RS per tahun — digunakan untuk hitung % dampak",
                        max_digits=18,
                        verbose_name="Anggaran farmasi tahunan baseline (IDR)",
                    ),
                ),
                (
                    "projection_horizon",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1 tahun"), (3, "3 tahun")],
                        default=3,
                        verbose_name="Horison proyeksi (tahun)",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical BIA Input",
                "verbose_name_plural": "historical BIA Inputs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="BIAResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "input_snapshot",
                    models.JSONField(help_text="BIAInput field values at compute time"),
                ),
                ("year1_drug_cost", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "year1_comparator_cost_displaced",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("year1_net_impact", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "year2_net_impact_interpolated",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "year3_drug_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "year3_comparator_cost_displaced",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "year3_net_impact",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("cumulative_impact", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "pct_of_annual_budget",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Cumulative impact divided by annual budget (×100 for percent)",
                        max_digits=8,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("cost_saving", "Cost-saving (penghematan)"),
                            ("manageable", "Manageable (<=10% anggaran)"),
                            ("significant", "Significant (10-50% anggaran)"),
                            ("prohibitive", "Prohibitive (>50% anggaran)"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("savings", "Penghematan bersih"),
                            ("mixed", "Campuran"),
                            ("cost_increase", "Beban biaya tambahan"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "budget_score",
                    models.PositiveSmallIntegerField(
                        help_text="0-100 contribution to traffic-light synthesis (20% weight)"
                    ),
                ),
                ("interpretation_text", models.TextField(blank=True, default="")),
                ("algorithm_version", models.CharField(default="1.0.0", max_length=16)),
                (
                    "computed_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bia_results",
                        to="cases.case",
                    ),
                ),
                (
                    "computed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bia_results_computed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "BIA Result",
                "verbose_name_plural": "BIA Results",
                "ordering": ["-computed_at"],
                "indexes": [
                    models.Index(
                        fields=["case", "-computed_at"], name="bia_biaresu_case_id_128103_idx"
                    )
                ],
            },
        ),
    ]
