# Generated by Django 5.2.14 on 2026-06-08 07:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPolicyBriefDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(help_text='Monotonically increasing per case. v1 is the first generation.')),
                ('status', models.CharField(choices=[('generating', 'Sedang diproses'), ('completed', 'Selesai'), ('failed', 'Gagal')], db_index=True, default='generating', max_length=16)),
                ('docx_path', models.CharField(blank=True, default='', max_length=512)),
                ('pdf_path', models.CharField(blank=True, default='', max_length=512)),
                ('docx_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('pdf_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('docx_size_bytes', models.PositiveIntegerField(default=0)),
                ('pdf_size_bytes', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source_recommendation_id', models.PositiveIntegerField(blank=True, help_text='ID of the Recommendation row used to generate this brief.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.case')),
                ('generated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Policy brief document',
                'verbose_name_plural': 'historical Policy brief documents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PolicyBriefDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(help_text='Monotonically increasing per case. v1 is the first generation.')),
                ('status', models.CharField(choices=[('generating', 'Sedang diproses'), ('completed', 'Selesai'), ('failed', 'Gagal')], db_index=True, default='generating', max_length=16)),
                ('docx_path', models.CharField(blank=True, default='', max_length=512)),
                ('pdf_path', models.CharField(blank=True, default='', max_length=512)),
                ('docx_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('pdf_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('docx_size_bytes', models.PositiveIntegerField(default=0)),
                ('pdf_size_bytes', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source_recommendation_id', models.PositiveIntegerField(blank=True, help_text='ID of the Recommendation row used to generate this brief.', null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_briefs', to='cases.case')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_briefs_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Policy brief document',
                'verbose_name_plural': 'Policy brief documents',
                'ordering': ('-generated_at',),
                'constraints': [models.UniqueConstraint(fields=('case', 'version'), name='unique_policy_brief_per_version')],
            },
        ),
    ]
