# Generated by Django 5.2.14 on 2026-08-23 03:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_caseversion_approval_id_caseversion_bia_result_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon_years', models.PositiveSmallIntegerField(default=1, help_text='Jumlah tahun proyeksi. Discounting memakai eksponen (t-1).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Horizon analisis (tahun)')),
                ('cost_discount_rate', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='mis. 0.03 untuk 3% per tahun', max_digits=9, verbose_name='Discount rate biaya')),
                ('outcome_discount_rate', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='mis. 0.03 untuk 3% per tahun', max_digits=9, verbose_name='Discount rate outcome/QALY')),
                ('wtp_threshold', models.DecimalField(decimal_places=4, default=Decimal('85000000.0000'), max_digits=20, verbose_name='WTP threshold (IDR per QALY)')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='economic_model', to='cases.case')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='economic_models_created', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='economic_models_edited', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Economic Model',
                'verbose_name_plural': 'Economic Models',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEconomicModel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('horizon_years', models.PositiveSmallIntegerField(default=1, help_text='Jumlah tahun proyeksi. Discounting memakai eksponen (t-1).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Horizon analisis (tahun)')),
                ('cost_discount_rate', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='mis. 0.03 untuk 3% per tahun', max_digits=9, verbose_name='Discount rate biaya')),
                ('outcome_discount_rate', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='mis. 0.03 untuk 3% per tahun', max_digits=9, verbose_name='Discount rate outcome/QALY')),
                ('wtp_threshold', models.DecimalField(decimal_places=4, default=Decimal('85000000.0000'), max_digits=20, verbose_name='WTP threshold (IDR per QALY)')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Economic Model',
                'verbose_name_plural': 'historical Economic Models',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEconomicParameter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('key', models.CharField(choices=[('drug_cost', 'Biaya obat per pasien per tahun'), ('event_probability', 'Probabilitas kejadian / rehospitalisasi'), ('event_cost', 'Biaya per kejadian / rawat inap'), ('other_cost', 'Biaya tambahan lain per pasien per tahun'), ('baseline_utility', 'Utility dasar'), ('event_disutility', 'Disutility kejadian'), ('eligible_population', 'Jumlah populasi eligible'), ('uptake', 'Uptake (proporsi eligible yang diobati)'), ('market_share', 'Market share (proporsi diobati yang memakai alternatif ini)')], help_text='Identifier kanonik yang dibaca oleh engine', max_length=40, verbose_name='Kunci parameter')),
                ('label', models.CharField(blank=True, default='', help_text='Nama tampilan; kosong = pakai label default dari key', max_length=160, verbose_name='Nama parameter')),
                ('alternative', models.CharField(choices=[('intervention', 'Intervensi'), ('comparator', 'Komparator'), ('shared', 'Bersama (kedua alternatif)')], default='shared', max_length=16)),
                ('year_index', models.PositiveSmallIntegerField(blank=True, help_text='Kosong = berlaku untuk semua tahun. Isi 1..horizon untuk nilai per-tahun.', null=True, verbose_name='Tahun ke-')),
                ('value', models.DecimalField(decimal_places=10, max_digits=28, verbose_name='Nilai')),
                ('unit', models.CharField(blank=True, default='', max_length=40, verbose_name='Satuan')),
                ('param_type', models.CharField(choices=[('cost', 'Biaya'), ('probability', 'Probabilitas'), ('utility', 'Utility'), ('disutility', 'Disutility'), ('rate', 'Rasio / tingkat'), ('count', 'Jumlah')], default='cost', max_length=16, verbose_name='Tipe')),
                ('data_status', models.CharField(choices=[('observed', 'Observed (data teramati)'), ('proxy', 'Proxy (pendekatan)'), ('assumption', 'Assumption (asumsi ilustratif)')], default='assumption', max_length=16, verbose_name='Status data')),
                ('source_reference', models.TextField(blank=True, default='', verbose_name='Sumber data')),
                ('source_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tahun sumber')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Catatan / asumsi')),
                ('version', models.PositiveIntegerField(default=1, help_text='Naik otomatis setiap kali nilai diedit', verbose_name='Versi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('economic_model', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='econ.economicmodel')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Economic Parameter',
                'verbose_name_plural': 'historical Economic Parameters',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EconomicParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('drug_cost', 'Biaya obat per pasien per tahun'), ('event_probability', 'Probabilitas kejadian / rehospitalisasi'), ('event_cost', 'Biaya per kejadian / rawat inap'), ('other_cost', 'Biaya tambahan lain per pasien per tahun'), ('baseline_utility', 'Utility dasar'), ('event_disutility', 'Disutility kejadian'), ('eligible_population', 'Jumlah populasi eligible'), ('uptake', 'Uptake (proporsi eligible yang diobati)'), ('market_share', 'Market share (proporsi diobati yang memakai alternatif ini)')], help_text='Identifier kanonik yang dibaca oleh engine', max_length=40, verbose_name='Kunci parameter')),
                ('label', models.CharField(blank=True, default='', help_text='Nama tampilan; kosong = pakai label default dari key', max_length=160, verbose_name='Nama parameter')),
                ('alternative', models.CharField(choices=[('intervention', 'Intervensi'), ('comparator', 'Komparator'), ('shared', 'Bersama (kedua alternatif)')], default='shared', max_length=16)),
                ('year_index', models.PositiveSmallIntegerField(blank=True, help_text='Kosong = berlaku untuk semua tahun. Isi 1..horizon untuk nilai per-tahun.', null=True, verbose_name='Tahun ke-')),
                ('value', models.DecimalField(decimal_places=10, max_digits=28, verbose_name='Nilai')),
                ('unit', models.CharField(blank=True, default='', max_length=40, verbose_name='Satuan')),
                ('param_type', models.CharField(choices=[('cost', 'Biaya'), ('probability', 'Probabilitas'), ('utility', 'Utility'), ('disutility', 'Disutility'), ('rate', 'Rasio / tingkat'), ('count', 'Jumlah')], default='cost', max_length=16, verbose_name='Tipe')),
                ('data_status', models.CharField(choices=[('observed', 'Observed (data teramati)'), ('proxy', 'Proxy (pendekatan)'), ('assumption', 'Assumption (asumsi ilustratif)')], default='assumption', max_length=16, verbose_name='Status data')),
                ('source_reference', models.TextField(blank=True, default='', verbose_name='Sumber data')),
                ('source_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tahun sumber')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Catatan / asumsi')),
                ('version', models.PositiveIntegerField(default=1, help_text='Naik otomatis setiap kali nilai diedit', verbose_name='Versi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='econ_params_created', to=settings.AUTH_USER_MODEL)),
                ('economic_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='econ.economicmodel')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='econ_params_edited', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Economic Parameter',
                'verbose_name_plural': 'Economic Parameters',
                'ordering': ['key', 'alternative', 'year_index'],
                'constraints': [models.UniqueConstraint(fields=('economic_model', 'key', 'alternative', 'year_index'), name='uniq_econ_param_key_alt_year')],
            },
        ),
    ]
