# Generated by Django 5.2.14 on 2026-08-23 03:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='economicparameter',
            name='uniq_econ_param_key_alt_year',
        ),
        migrations.AddConstraint(
            model_name='economicparameter',
            constraint=models.UniqueConstraint(fields=('economic_model', 'key', 'alternative', 'year_index'), name='uniq_econ_param_key_alt_year', nulls_distinct=False),
        ),
    ]
