# Generated by Django 5.2.14 on 2026-08-23 03:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_caseversion_approval_id_caseversion_bia_result_id_and_more'),
        ('econ', '0002_remove_economicparameter_uniq_econ_param_key_alt_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EconDeterministicResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_snapshot', models.JSONField(help_text='Resolved engine inputs at compute time')),
                ('total_cost_intervention', models.DecimalField(decimal_places=10, max_digits=30)),
                ('total_cost_comparator', models.DecimalField(decimal_places=10, max_digits=30)),
                ('total_qaly_intervention', models.DecimalField(decimal_places=10, max_digits=18)),
                ('total_qaly_comparator', models.DecimalField(decimal_places=10, max_digits=18)),
                ('incremental_cost', models.DecimalField(decimal_places=10, max_digits=30)),
                ('incremental_qaly', models.DecimalField(decimal_places=10, max_digits=18)),
                ('icer', models.DecimalField(blank=True, decimal_places=10, help_text='Null when incremental QALY is zero (N/A, no division)', max_digits=30, null=True)),
                ('nmb_intervention', models.DecimalField(decimal_places=10, max_digits=30)),
                ('nmb_comparator', models.DecimalField(decimal_places=10, max_digits=30)),
                ('inb', models.DecimalField(decimal_places=10, max_digits=30)),
                ('wtp_threshold_used', models.DecimalField(decimal_places=4, max_digits=20)),
                ('decision_code', models.CharField(max_length=24)),
                ('is_cost_effective', models.BooleanField()),
                ('is_dominant', models.BooleanField()),
                ('is_dominated', models.BooleanField()),
                ('per_year', models.JSONField(default=dict)),
                ('cost_breakdown', models.JSONField(default=dict)),
                ('interpretation_text', models.TextField(blank=True, default='')),
                ('algorithm_version', models.CharField(default='2.0.0', max_length=16)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='econ_deterministic_results', to='cases.case')),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='econ_results_computed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deterministic Result',
                'verbose_name_plural': 'Deterministic Results',
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['case', '-computed_at'], name='econ_econde_case_id_9b9c2f_idx')],
            },
        ),
    ]
