# Generated by Django 5.2.14 on 2026-08-23 08:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_caseversion_approval_id_caseversion_bia_result_id_and_more'),
        ('econ', '0003_econdeterministicresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='economicmodel',
            name='annual_budget_baseline',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Dasar perhitungan % dampak anggaran (BIA)', max_digits=20, null=True, verbose_name='Anggaran farmasi tahunan baseline (IDR)'),
        ),
        migrations.AddField(
            model_name='historicaleconomicmodel',
            name='annual_budget_baseline',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Dasar perhitungan % dampak anggaran (BIA)', max_digits=20, null=True, verbose_name='Anggaran farmasi tahunan baseline (IDR)'),
        ),
        migrations.CreateModel(
            name='EconBIAResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_snapshot', models.JSONField(help_text='Resolved BIA inputs at compute time')),
                ('cumulative_net_impact', models.DecimalField(decimal_places=10, max_digits=30)),
                ('pct_of_total_baseline', models.DecimalField(decimal_places=4, max_digits=12)),
                ('annual_budget_baseline', models.DecimalField(decimal_places=4, max_digits=20)),
                ('severity', models.CharField(max_length=16)),
                ('budget_score', models.PositiveSmallIntegerField(help_text='0-100 contribution to the traffic-light synthesis (20% weight)')),
                ('per_year', models.JSONField(default=list)),
                ('interpretation_text', models.TextField(blank=True, default='')),
                ('algorithm_version', models.CharField(default='1.0.0', max_length=16)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='econ_bia_results', to='cases.case')),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='econ_bia_results_computed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BIA Result (econ)',
                'verbose_name_plural': 'BIA Results (econ)',
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['case', '-computed_at'], name='econ_econbi_case_id_844755_idx')],
            },
        ),
    ]
