# Generated by Django 5.2.14 on 2026-08-23 08:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_caseversion_approval_id_caseversion_bia_result_id_and_more'),
        ('econ', '0004_economicmodel_annual_budget_baseline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='economicparameter',
            name='dist_param1',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='alpha (beta) / shape (gamma) / mean (lognormal, normal)', max_digits=28, null=True, verbose_name='Parameter distribusi 1'),
        ),
        migrations.AddField(
            model_name='economicparameter',
            name='dist_param2',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='beta (beta) / scale (gamma) / SE (lognormal, normal)', max_digits=28, null=True, verbose_name='Parameter distribusi 2'),
        ),
        migrations.AddField(
            model_name='economicparameter',
            name='distribution',
            field=models.CharField(choices=[('fixed', 'Tetap (tidak disampel)'), ('beta', 'Beta (probabilitas/utility)'), ('gamma', 'Gamma (biaya)'), ('lognormal', 'Log-normal (biaya)'), ('normal', 'Normal')], default='fixed', max_length=16, verbose_name='Distribusi PSA'),
        ),
        migrations.AddField(
            model_name='historicaleconomicparameter',
            name='dist_param1',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='alpha (beta) / shape (gamma) / mean (lognormal, normal)', max_digits=28, null=True, verbose_name='Parameter distribusi 1'),
        ),
        migrations.AddField(
            model_name='historicaleconomicparameter',
            name='dist_param2',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='beta (beta) / scale (gamma) / SE (lognormal, normal)', max_digits=28, null=True, verbose_name='Parameter distribusi 2'),
        ),
        migrations.AddField(
            model_name='historicaleconomicparameter',
            name='distribution',
            field=models.CharField(choices=[('fixed', 'Tetap (tidak disampel)'), ('beta', 'Beta (probabilitas/utility)'), ('gamma', 'Gamma (biaya)'), ('lognormal', 'Log-normal (biaya)'), ('normal', 'Normal')], default='fixed', max_length=16, verbose_name='Distribusi PSA'),
        ),
        migrations.CreateModel(
            name='EconPSAResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_snapshot', models.JSONField(help_text='Run config + resolved base params')),
                ('n_simulations', models.PositiveIntegerField()),
                ('random_seed', models.BigIntegerField()),
                ('wtp_base', models.DecimalField(decimal_places=4, max_digits=20)),
                ('prob_cost_effective_base', models.DecimalField(decimal_places=4, max_digits=6)),
                ('mean_incremental_cost', models.DecimalField(decimal_places=10, max_digits=30)),
                ('mean_incremental_qaly', models.DecimalField(decimal_places=10, max_digits=18)),
                ('ceac', models.JSONField(default=list)),
                ('scatter', models.JSONField(default=list)),
                ('base_case_incremental_cost', models.DecimalField(decimal_places=10, max_digits=30)),
                ('base_case_incremental_qaly', models.DecimalField(decimal_places=10, max_digits=18)),
                ('interpretation_text', models.TextField(blank=True, default='')),
                ('algorithm_version', models.CharField(default='1.0.0', max_length=16)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='econ_psa_results', to='cases.case')),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='econ_psa_results_computed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PSA Result',
                'verbose_name_plural': 'PSA Results',
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['case', '-computed_at'], name='econ_econps_case_id_62bde4_idx')],
            },
        ),
    ]
