# Generated by Django 5.2.14 on 2026-09-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0005_economicparameter_dist_param1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='econbiaresult',
            name='scenarios',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='econdeterministicresult',
            name='clinical',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='economicparameter',
            name='key',
            field=models.CharField(choices=[('drug_cost', 'Biaya obat per pasien per tahun'), ('event_probability', 'Probabilitas kejadian / rehospitalisasi'), ('event_cost', 'Biaya per kejadian / rawat inap'), ('other_cost', 'Biaya tambahan lain per pasien per tahun'), ('baseline_utility', 'Utility dasar'), ('event_disutility', 'Disutility kejadian'), ('eligible_population', 'Jumlah populasi eligible'), ('uptake', 'Uptake (proporsi eligible yang diobati)'), ('market_share', 'Market share (opsional; default 1,0)'), ('uptake_low', 'Uptake skenario rendah'), ('uptake_medium', 'Uptake skenario menengah'), ('uptake_high', 'Uptake skenario tinggi'), ('median_los', 'Median length of stay (hari/admisi)')], help_text='Identifier kanonik yang dibaca oleh engine', max_length=40, verbose_name='Kunci parameter'),
        ),
        migrations.AlterField(
            model_name='historicaleconomicparameter',
            name='key',
            field=models.CharField(choices=[('drug_cost', 'Biaya obat per pasien per tahun'), ('event_probability', 'Probabilitas kejadian / rehospitalisasi'), ('event_cost', 'Biaya per kejadian / rawat inap'), ('other_cost', 'Biaya tambahan lain per pasien per tahun'), ('baseline_utility', 'Utility dasar'), ('event_disutility', 'Disutility kejadian'), ('eligible_population', 'Jumlah populasi eligible'), ('uptake', 'Uptake (proporsi eligible yang diobati)'), ('market_share', 'Market share (opsional; default 1,0)'), ('uptake_low', 'Uptake skenario rendah'), ('uptake_medium', 'Uptake skenario menengah'), ('uptake_high', 'Uptake skenario tinggi'), ('median_los', 'Median length of stay (hari/admisi)')], help_text='Identifier kanonik yang dibaca oleh engine', max_length=40, verbose_name='Kunci parameter'),
        ),
    ]
