# Generated by Django 5.2.14 on 2026-09-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0006_econbiaresult_scenarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='econbiaresult',
            name='annual_budget_baseline',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='econbiaresult',
            name='budget_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0-100 contribution to the traffic-light synthesis (20% weight)', null=True),
        ),
    ]
