# Generated by Django 5.2.14 on 2026-09-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0007_alter_econbiaresult_annual_budget_baseline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicparameter',
            name='data_status',
            field=models.CharField(choices=[('observed', 'Observed (data teramati)'), ('proxy', 'Proxy (pendekatan)'), ('assumption', 'Assumption (asumsi ilustratif)'), ('validated', 'Validated (terverifikasi terhadap sumber)')], default='assumption', max_length=16, verbose_name='Status data'),
        ),
        migrations.AlterField(
            model_name='historicaleconomicparameter',
            name='data_status',
            field=models.CharField(choices=[('observed', 'Observed (data teramati)'), ('proxy', 'Proxy (pendekatan)'), ('assumption', 'Assumption (asumsi ilustratif)'), ('validated', 'Validated (terverifikasi terhadap sumber)')], default='assumption', max_length=16, verbose_name='Status data'),
        ),
    ]
