# Generated by Django 5.2.14 on 2026-10-06 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0008_alter_economicparameter_data_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicmodel',
            name='bia_horizon_years',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Kosong = sama dengan horizon analisis CEA.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Horizon BIA (tahun)'),
        ),
        migrations.AddField(
            model_name='historicaleconomicmodel',
            name='bia_horizon_years',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Kosong = sama dengan horizon analisis CEA.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Horizon BIA (tahun)'),
        ),
    ]
